USER:
  RNumber:
  Password: 
  UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246

LOGIN:
  PortalURL: https://toledo.kuleuven.be/portal/
  DashboardURL: https://toledo.kuleuven.be/dashboard/
  AuthorizationEndpoint: https://idp.kuleuven.be/auth/realms/kuleuven/protocol/openid-connect/auth/
  TokenEndpoint: https://idp.kuleuven.be/auth/realms/kuleuven/protocol/openid-connect/token/
  BrokerEndpoint: https://idp.kuleuven.be/auth/realms/kuleuven/broker/saml-p-idp/endpoint

API:
  UpcomingEndpoint: https://toledo.kuleuven.be/portal/api/upcoming/
  EnrollmentsEndpoint: https://toledo.kuleuven.be/portal/api/enrollments/
  EventsEndpoint: https://toledo.kuleuven.be/portal/api/events/
  TodoEndpoint: https://learning-analytics-cygnus.icts.kuleuven.be/api/users/availableUserContentState/
  

API_TO_DO:
  Task: x-bb-assignment
  Test: x-bb-asmt-test-link
  Various: x-bb-asmt-survey-link


OUT:
  OutputDir:



